USE [MathaDist]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER TABLE [dbo].[SReturn] ALTER COLUMN CustId INT;
GO

ALTER TABLE [dbo].[SPayment] ALTER COLUMN CustId INT;
GO

ALTER TABLE [dbo].[SOrder] ALTER COLUMN CustId INT;
GO

ALTER TABLE [dbo].[Sales] ALTER COLUMN CustId INT;
GO

ALTER TABLE [dbo].[Customer] ALTER COLUMN CustId INT;
GO
