USE [Matha]
GO

/****** Object:  Table [dbo].[PPayment]    Script Date: 25-Aug-18 9:42:48 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PPayment]
(
	[SerialId] [int] IDENTITY(1,1) NOT NULL,
	[ReceiptNum] [nvarchar](20) NOT NULL,
	[Mode] [nvarchar](10) NULL,
	[Dated] [datetime] NULL,
	[RefNum] [nvarchar](200) NULL,
	[TxnId] [int] NOT NULL,
	[Status] [int] NULL,
	PRIMARY KEY CLUSTERED 
	(
		[SerialId] ASC
	)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	CONSTRAINT [IX_PPayment_1] UNIQUE NONCLUSTERED 
	(
		[ReceiptNum] ASC
	)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
