sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i createTable_Customer.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i createTable_Addresses.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i createTable_BankAccounts.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i createTable_CashBook.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i createTable_CashHead.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i createTable_Districts.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i createTable_PPayment.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i createTable_PReturn.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i createTable_PTransactions.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i createTable_Purchase.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i createTable_Sales.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i createTable_SOrder.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i createTable_SPayment.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i createTable_SReturn.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i createTable_State.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i createTable_STransactions.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i createTable_Supplier.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i create_Seq_PReturnSeq.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i create_Seq_PurchaseSeq.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i create_Seq_SalesSeq.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i create_Seq_SOrderSeq.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i create_Seq_SReturnSeq.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i createTable_Book.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i createTable_SOrderDet.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i createTable_SalesDet.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i createTable_SReturnDet.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i createTable_PurDet.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i createTable_PReturnDet.sql

sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i insert_Supplier.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i insert_States.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i insert_Districts.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i insert_BankAccounts.sql
sqlcmd -S .\SQLEXPRESS2014 /d Matha /E /i insert_Addresses.sql
