USE [MathaNew]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER TABLE [dbo].[SReturn] ADD [TxnId] INT NULL;
GO

ALTER TABLE [dbo].[SReturn] ALTER COLUMN [SerialId] INT NOT NULL;
GO

ALTER TABLE [dbo].[SReturn] ADD CONSTRAINT SReturn_PK PRIMARY KEY([SerialId]);
GO
