sqlcmd /d Matha /E /i alterBook.sql
sqlcmd /d Matha /E /i alterPublisher.sql
sqlcmd /d Matha /E /i alterSales.sql
sqlcmd /d Matha /E /i alterSchool.sql
sqlcmd /d Matha /E /i alterSOrder.sql
sqlcmd /d Matha /E /i alterSOrderDet.sql
sqlcmd /d Matha /E /i createBookPurchase.sql
sqlcmd /d Matha /E /i createCashBook.sql
sqlcmd /d Matha /E /i createCashHead.sql
sqlcmd /d Matha /E /i createDistricts.sql
sqlcmd /d Matha /E /i createPPayment.sql
sqlcmd /d Matha /E /i createPTransactions.sql
sqlcmd /d Matha /E /i createPurchaseReturn.sql
sqlcmd /d Matha /E /i createSchoolReturn.sql
sqlcmd /d Matha /E /i createSPayment.sql
sqlcmd /d Matha /E /i createState.sql
sqlcmd /d Matha /E /i createSTransactions.sql
sqlcmd /d Matha /E /i create_Seq_SalesSeq.sql
sqlcmd /d Matha /E /i create_Seq_SalesSerialSeq.sql
sqlcmd /d Matha /E /i create_Seq_SOrderSeq.sql
sqlcmd /d Matha /E /i deleteDup.sql
