USE [MathaDist]
GO

/****** Object:  Table [dbo].[State]    Script Date: 25-Aug-18 12:10:01 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[State](
	[name] [varchar](50) NOT NULL,
	CONSTRAINT [PK_States] PRIMARY KEY CLUSTERED 
	(
		[name] ASC
	)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


